#pragma once

/**
@file
Subclass of CDCM6208_CONTROL, which is generated by wxFormBuilder.
*/

#include "lime/LimeSuite.h"
#include "CDCM6208_panelgui.h"

class CDCM6208_framegui : public CDCM6208_CONTROL
{

public:
   CDCM6208_framegui( wxWindow* parent );
   CDCM6208_framegui(  wxWindow* parent, wxWindowID id , const wxString& title , const wxPoint& pos , const wxSize& size , long style );
     virtual void Initialize(lms_device_t* pCtrPort);
protected:
     lms_device_t* device;
};
