#ifndef __dlgConnectionSettings__
#define __dlgConnectionSettings__

/**
@file
Subclass of dlgConnectionSettings, which is generated by wxFormBuilder.
*/

#include "utilities_gui.h"
#include "LimeSuite.h"
//// end generated include
namespace lime{
}

/** Implementing dlgConnectionSettings */
class dlgConnectionSettings : public dlgConnectionSettings_view
{
	protected:
		// Handlers for dlgConnectionSettings events.
		void GetDeviceList( wxInitDialogEvent& event );
		void OnConnect( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
		void OnDisconnect( wxCommandEvent& event );
	public:
		/** Constructor */
		dlgConnectionSettings( wxWindow* parent );
	//// end generated class members
        void SetConnectionManagers(lms_device_t** lms);
	protected:
        lms_device_t** lmsControl;
        int lmsOpenedIndex;
};

#endif // __dlgConnectionSettings__
