#ifndef __dlgDeviceInfo__
#define __dlgDeviceInfo__

/**
@file
Subclass of dlgDeviceInfo_view, which is generated by wxFormBuilder.
*/

#include "utilities_gui.h"
#include "lime/LimeSuite.h"
//// end generated include
/** Implementing dlgDeviceInfo_view */
class dlgDeviceInfo : public dlgDeviceInfo_view
{
	protected:
		// Handlers for dlgDeviceInfo_view events.
		void OnGetInfo( wxCommandEvent& event );
	public:
		/** Constructor */
		dlgDeviceInfo( wxWindow* parent );
	//// end generated class members
        dlgDeviceInfo(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString &title = wxEmptyString, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long styles = 0);
        virtual void Initialize(lms_device_t* lms);
    protected:
        lms_device_t* lmsControl;

};

#endif // __dlgDeviceInfo__
