#ifndef __pnlMiniLog__
#define __pnlMiniLog__

/**
@file
Subclass of pnlMiniLog_view, which is generated by wxFormBuilder.
*/

#include "utilities_gui.h"
//// end generated include
#include <deque>
#include <utility> //pair
#include "Logger.h"

/** Implementing pnlMiniLog_view */
class pnlMiniLog : public pnlMiniLog_view
{
	public:
		/** Constructor */
		pnlMiniLog(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = wxTAB_TRAVERSAL);
        virtual void OnBtnClearClicked(wxCommandEvent& event);
        virtual void OnShowFullLog(wxCommandEvent& event);
	//// end generated class members
        void HandleMessage(wxCommandEvent &event);
		virtual void OnUpdateGUI(wxUpdateUIEvent& event);

		protected:
            wxTextAttr mDefaultStyle;
            std::deque<wxString> mAllMessages;
            std::deque<std::pair<lime::LogLevel, wxString>> mMessageList;
			int mNewMessages;	
};

#endif // __pnlMiniLog__
