#ifndef __pnlMiniLog__
#define __pnlMiniLog__

/**
@file
Subclass of pnlMiniLog_view, which is generated by wxFormBuilder.
*/

#include "utilities_gui.h"
//// end generated include
#include <vector>

/** Implementing pnlMiniLog_view */
class pnlMiniLog : public pnlMiniLog_view
{
	public:
		/** Constructor */
		pnlMiniLog(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = wxTAB_TRAVERSAL);
	//// end generated class members
		//virtual void HandleMessage(const LMS_Message &msg);
		virtual void OnUpdateGUI(wxUpdateUIEvent& event);

		protected:
			std::vector<wxString> mMessageList;
			int mNewMessages;
	
};

#endif // __pnlMiniLog__
