#ifndef __SPI_wxgui__
#define __SPI_wxgui__

/**
@file
Subclass of SPI_view, which is generated by wxFormBuilder.
*/

#include "utilities_gui.h"

//// end generated include
class IConnection;
/** Implementing SPI_view */
class SPI_wxgui : public SPI_view
{
	protected:
		// Handlers for SPI_view events.
		void onLMSwrite( wxCommandEvent& event );
		void onLMSread( wxCommandEvent& event );
		void onBoardWrite( wxCommandEvent& event );
		void OnBoardRead( wxCommandEvent& event );
	public:
		/** Constructor */
		SPI_wxgui( wxWindow* parent );
	//// end generated class members
        SPI_wxgui(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString &title = wxEmptyString, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long styles = 0);
        virtual void Initialize(IConnection* pCtrPort, IConnection* pDataPort);
    protected:
        IConnection* ctrPort;
        IConnection* dataPort;
};

#endif // __SPI_wxgui__
