#ifndef LMS7SUITE_EVENT_IDS_H
#define LMS7SUITE_EVENT_IDS_H

#include <wx/wx.h>

wxDECLARE_EVENT(CONTROL_PORT_CONNECTED, wxCommandEvent);
wxDECLARE_EVENT(DATA_PORT_CONNECTED, wxCommandEvent);
wxDECLARE_EVENT(CONTROL_PORT_DISCONNECTED, wxCommandEvent);
wxDECLARE_EVENT(DATA_PORT_DISCONNECTED, wxCommandEvent);
wxDECLARE_EVENT(CGEN_FREQUENCY_CHANGED, wxCommandEvent);

#endif