#ifndef __fftviewer_frFFTviewer__
#define __fftviewer_frFFTviewer__

/**
@file
Subclass of frFFTviewer, which is generated by wxFormBuilder.
*/

#include "fftviewer_wxgui.h"
class mpPolygon;
class mpFXYVector;
class StreamerLTE;
class LMScomms;
#include <wx/timer.h>
//// end generated include

/** Implementing frFFTviewer */
class fftviewer_frFFTviewer : public frFFTviewer
{
	protected:
		// Handlers for frFFTviewer events.
		void OnFFTsamplesCountChanged( wxSpinEvent& event );
		void OnWindowFunctionChanged( wxCommandEvent& event );
		void OnbtnStartStop( wxCommandEvent& event );

        void OnUpdatePlots(wxTimerEvent& event);
	public:
		/** Constructor */
		fftviewer_frFFTviewer( wxWindow* parent );
        ~fftviewer_frFFTviewer();
	//// end generated class members
        void Initialize(LMScomms* pDataPort);
        void SetNyquistFrequency(float freqMHz);

        void StartStreaming();
        void StopStreaming();
	
protected:
    wxString printDataRate(float dataRate);

    LMScomms* mDataPort;
    mpPolygon* mTimeDomainIdata;
    mpPolygon* mTimeDomainQdata;
    mpFXYVector* mConstelationData;
    mpPolygon* mFFTdata;
    StreamerLTE* mLTEstreamer;
    wxTimer* mGUIupdater;
};

#endif // __fftviewer_frFFTviewer__
