#ifndef __lms7002_pnlMCU_BD_view__
#define __lms7002_pnlMCU_BD_view__

/**
@file
Subclass of pnlMCU_BD_view, which is generated by wxFormBuilder.
*/

#include "lms7002_wxgui.h"

//// end generated include
class MCU_BD;
#include <wx/timer.h>
#include <thread>
/** Implementing pnlMCU_BD_view */
class lms7002_pnlMCU_BD_view : public pnlMCU_BD_view
{
	protected:
		// Handlers for pnlMCU_BD_view events.
		void OnButton_LOADHexClick( wxCommandEvent& event );
		void OnchkResetClick( wxCommandEvent& event );
		void OnbtnStartProgrammingClick( wxCommandEvent& event );
		void OnbtnLoadTestFileClick( wxCommandEvent& event );
		void OnbtnRunTestClick( wxCommandEvent& event );
		void OnDebugModeClick( wxCommandEvent& event );
		void OnRunInstruction( wxCommandEvent& event );
		void OnResetPCClick( wxCommandEvent& event );
		void OnViewSFRsClick( wxCommandEvent& event );
		void OnViewIRAMClick( wxCommandEvent& event );
		void OnEraseIRAMClick( wxCommandEvent& event );
		void OnSelDivSelect( wxCommandEvent& event );
		void Onm_cCtrlBasebandSelect( wxCommandEvent& event );
		void Onm_cCtrlMCU_BDSelect( wxCommandEvent& event );
		void OnRegWriteRead( wxCommandEvent& event );
	public:
		/** Constructor */
		lms7002_pnlMCU_BD_view( wxWindow* parent );
	//// end generated class members
        ~lms7002_pnlMCU_BD_view();
        void Initialize(MCU_BD* pMCUcontrol);
        void OnProgressPoll(wxTimerEvent& evt);
protected:    
    void OnReadIRAMfinished(wxThreadEvent &event);
    void OnEraseIRAMfinished(wxThreadEvent &event);
    void OnReadSFRfinished(wxThreadEvent &event);
    void OnProgrammingfinished(wxThreadEvent &event);
    bool mThreadWorking;
    std::thread mWorkerThread;
    wxTimer* progressPooler;
    MCU_BD* mcuControl;
    int m_iTestNo;
    int m_iInstrNo;
    int m_iPCvalue;
    int m_iDebug;
    int m_iMode0;
    int m_iMode1;

    int m_iTestResultFileLine;
    int TestResultArray_code[256];
    int TestResultArray_address[256];
    int TestResultArray_value[256];

    unsigned short m_iRegAddress;
    int m_iRegRead;
    unsigned short m_iRegData;

    int m_bLoadedProd;
    int m_bLoadedDebug;
};

#endif // __lms7002_pnlMCU_BD_view__
