#ifndef __lms7002_pnlBuffers_view__
#define __lms7002_pnlBuffers_view__

/**
@file
Subclass of pnlBuffers_view, which is generated by wxFormBuilder.
*/

#include "lms7002_wxgui.h"
#include "lime/LimeSuite.h"
//// end generated include
namespace lime{
}
/** Implementing pnlBuffers_view */
class lms7002_pnlBuffers_view : public pnlBuffers_view
{
	protected:
		// Handlers for pnlBuffers_view events.
		void OnGPIOchanged( wxCommandEvent& event );
	public:
		/** Constructor */
		lms7002_pnlBuffers_view( wxWindow* parent );
	//// end generated class members
        lms7002_pnlBuffers_view(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = wxTAB_TRAVERSAL);
        void Initialize(lms_device_t* pSerPort);
        void UpdateGUI();
    protected:

        lms_device_t* lmsControl;
};

#endif // __lms7002_pnlBuffers_view__
