#ifndef __lms7002_pnlSPI_view__
#define __lms7002_pnlSPI_view__

/**
@file
Subclass of pnlSPI_view, which is generated by wxFormBuilder.
*/

#include "lms7002_wxgui.h"

//// end generated include
class LMScomms;

/** Implementing pnlSPI_view */
class lms7002_pnlSPI_view : public pnlSPI_view
{
	protected:
		// Handlers for pnlSPI_view events.
		void onLMSwrite( wxCommandEvent& event );
		void onLMSread( wxCommandEvent& event );

        LMScomms* ctrPort;
        LMScomms* dataPort;
	public:
		/** Constructor */
        lms7002_pnlSPI_view(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = wxTAB_TRAVERSAL);
        void UpdateGUI();
        void Initialize(LMScomms* ctr, LMScomms* data);
	//// end generated class members
	
};

#endif // __lms7002_pnlSPI_view__
