#ifndef __lms7002_pnlBIAS_view__
#define __lms7002_pnlBIAS_view__

/**
@file
Subclass of pnlBIAS_view, which is generated by wxFormBuilder.
*/

#include "lms7002_wxgui.h"

//// end generated include
#include <map>
#include "LMS7002M_parameters.h"
namespace lime{
class LMS7002M;
}
/** Implementing pnlBIAS_view */
class lms7002_pnlBIAS_view : public pnlBIAS_view
{
	protected:
		// Handlers for pnlBIAS_view events.
		void ParameterChangeHandler( wxCommandEvent& event );
	public:
		/** Constructor */
		lms7002_pnlBIAS_view( wxWindow* parent );
	//// end generated class members
	lms7002_pnlBIAS_view(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = wxTAB_TRAVERSAL);
    void Initialize(lime::LMS7002M* pControl);
    void UpdateGUI();
protected:
    lime::LMS7002M* lmsControl;
	std::map<wxWindow*, lime::LMS7Parameter> wndId2Enum;
};

#endif // __lms7002_pnlBIAS_view__
