#ifndef __lms7002_pnlTRF_view__
#define __lms7002_pnlTRF_view__

/**
@file
Subclass of pnlTRF_view, which is generated by wxFormBuilder.
*/

#include "lms7002_wxgui.h"

//// end generated include
#include <map>
#include "lms7_api.h"
namespace lime{

}
/** Implementing pnlTRF_view */
class lms7002_pnlTRF_view : public pnlTRF_view
{
	protected:
		// Handlers for pnlTRF_view events.
		void ParameterChangeHandler( wxCommandEvent& event );
		void OnBandChange( wxCommandEvent& event );
	public:
		/** Constructor */
		lms7002_pnlTRF_view( wxWindow* parent );
	//// end generated class members
	lms7002_pnlTRF_view(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = wxTAB_TRAVERSAL);
    void Initialize(lms_device* pControl);
    void UpdateGUI();
protected:
    lms_device* lmsControl;
	std::map<wxWindow*, LMS7Parameter> wndId2Enum;
};

#endif // __lms7002_pnlTRF_view__
