# List of source files
SOURCES = 	DPDTest.cpp dlgADPDControls.cpp  nrc.cpp

# List of header files
HEADERS = 	../include/DPDTest.h ../include/dlgADPDControls.h ../include/nrc.h \
		../kissFFT/kiss_fft.h ../libT800/T800.h \
		../include/iniParser.h

# Module name. The executable to create is $(MODULE).x
MODULE = DPDTest.cpp

# Compiler flags
CFLAGS = wx-config --cxxflags --libs

# User defined include directories
#UINCDIRS = -I/home/srdjan/CAT/include -I/home/srdjan/SCProjects/include

# User defined lib directories
#ULIBDIRS = -L/home/srdjan/CAT/lib

# If we need some more libraris on top of -lsystemc -lm
#ULIBS = -lcat

# Additional files to remove when we 'make clean'
#UCLEAN = rm -f ../work/*.fft ../work/*.mgp ../work/*.log ../work/*.ampm ../work/*.amgd

# Additional files to remove when we 'make cleanall'
#UCLEANALL = rm -f ../work/*.x

# The rest is done in here
#include /usr/local/systemc231a/Makefile.defs
