#!/bin/bash

echo -n "Uninstall Lime Suite menu launcher...	"
if [ -x /usr/bin/xdg-desktop-menu ] ; then
    xdg-desktop-menu uninstall lime-suite.desktop || true
    echo "OK"
else
    echo "FAIL (missing xdg-desktop-menu)"
fi

echo -n "Uninstall Lime Suite icon resources...	"
if [ -x /usr/bin/xdg-icon-resource ] ; then
    for theme in hicolor gnome; do
        for size in 16 22 32 48 64 128; do
            xdg-icon-resource uninstall --noupdate --context apps --theme ${theme} --size ${size} lime-suite || true
        done
    done
    xdg-icon-resource forceupdate || true
    echo "OK"
else
    echo "FAIL (missing xdg-icon-resource)"
fi
